import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion } from "framer-motion";

//form validation
//router

export default function Home() {
  //router
  const router = useRouter();

  //creating from
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "",
      terms: "",
    },
    //validating form

    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less")
        .required("Name is required"),
      email: Yup.string().email("Invalid Email").required("Email is required"),
      country: Yup.string("Please select a country"),
      terms: Yup.array().required("Please tick the checkbox"),
    }),

    // submit
    onSubmit: (values) => {
      // alert(JSON.stringify(values, null, 2));
      router.push({
        pathname: "/success",
        query: values,
      });
    },
  });

  // console.log(formik.errors);

  // console.log(formik.values);
  return (
    //framer-motion

    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form
          className="bg-white flex rounded-lg w-1/2 font-latoRegular"
          onSubmit={formik.handleSubmit}
        >
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-latoBold">Let's get started</h1>
            <p className="text-lg text-gray-500">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident
              natus facere maiores error distinctio et adipisci eos! Doloremque
              quisquam id, nam quam amet accusamus voluptatibus delectus libero
              eius quia hic.
            </p>
            <div className="mt-6">
              {/* Name input field */}
              <div className="pb-4">
                <label
                  htmlFor="name"
                  className={`text-gray-900 block pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  }`}
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name:"}
                </label>
                <input
                  type="text"
                  name="name"
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  value={formik.values.name}
                  placeholder="Enter your name"
                  className="bg-white "
                />
              </div>
              {/* Name email field */}
              <div className="pb-4">
                <label
                  htmlFor="email"
                  className={`text-gray-900 block pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                >
                  {formik.errors.email ? formik.errors.email : "Email:"}
                </label>
                <input
                  type="email"
                  name="email"
                  placeholder="Enter your email"
                  className="bg-white "
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  value={formik.values.email}
                />
              </div>
              {/* Name country field */}
              <div className="pb-4">
                <label htmlFor="country" className="text-gray-900 block pb-2">
                  Country:
                </label>
                <select
                  name="country"
                  id="country"
                  className=""
                  onChange={formik.handleChange}
                  value={formik.values.country}
                >
                  <option value="United States">United States</option>
                  <option value="Pakistan">Pakistan</option>
                  <option value="India">India</option>
                  <option value="South Africa">South Africa</option>
                </select>
              </div>
              {/* Name terms of service field */}
              <div className="pb-4">
                <label
                  htmlFor="terms"
                  className={`text-gray-900 block pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : ""
                  }`}
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms"}
                </label>
                <div className="flex items-start gap-2 pt-2">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    className="text-teal-500 border-2"
                    onChange={formik.handleChange}
                  />
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Libero fugit exercitationem voluptatibus vitae, nihil ipsam
                    alias voluptatum dolorem cumque nobis delectus quisquam
                    repellendus quaerat explicabo totam deleniti quis, quidem
                    officia?
                  </p>
                </div>
              </div>
              <div>
                <button
                  type="submit"
                  className="bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-md w-full"
                >
                  Start Today!
                </button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </motion.div>
  );
}
